version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: webai-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      webapp:
        condition: service_healthy
    restart: always
    networks:
      - webai-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  webapp:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: webai-app
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - CLAUDE_API_URL=http://claude-api:8000
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-4}
      - GUNICORN_THREADS=${GUNICORN_THREADS:-2}
    volumes:
      - ./claude-config:/home/app/.config/claude:rw
      - ./logs/webapp:/app/logs:rw
    depends_on:
      claude-api:
        condition: service_healthy
    restart: always
    networks:
      - webai-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  claude-api:
    build:
      context: ./claude-api
      dockerfile: Dockerfile
    container_name: webai-claude-api
    expose:
      - "8000"
    environment:
      - PORT=8000
      - PRODUCTION=true
      - MOCK_MODE=false
    volumes:
      - ./claude-config:/root/.config/claude:rw
      - ./claude-home:/root/.claude:rw
    restart: always
    networks:
      - webai-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  certbot:
    image: certbot/certbot:latest
    container_name: webai-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
      - ./logs/certbot:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always
    networks:
      - webai-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  webai-network:
    driver: bridge