#!/bin/bash

echo "🚀 Claude Code Actions クイックテスト"
echo "===================================="
echo ""
echo "以下のURLにアクセスして、手動でテストを実行してください："
echo ""
echo "1️⃣ 新しいIssueを作成:"
echo "   https://github.com/RyotaKuzuya/webai-search-service/issues/new"
echo ""
echo "2️⃣ タイトル:"
echo "   Public化成功テスト"
echo ""
echo "3️⃣ 本文:"
echo "   テスト用のIssueです"
echo ""
echo "4️⃣ Issueを作成したら、以下をコメント:"
echo ""
echo "---コピー用---"
echo "@claude"
echo ""
echo "こんにちは！リポジトリがPublicになりました。"
echo "GitHub Actionsが無料で動作することを確認しています。"
echo "正常に応答できますか？"
echo "---ここまで---"
echo ""
echo "5️⃣ 確認場所:"
echo "   Actions: https://github.com/RyotaKuzuya/webai-search-service/actions"
echo "   Issues: https://github.com/RyotaKuzuya/webai-search-service/issues"
echo ""
echo "✅ 成功の基準:"
echo "   - 課金エラーが出ない"
echo "   - Claudeから返信が来る"
echo "   - GitHub Actionsが実行される"