name: Simple Claude Test

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Test message'
        required: true
        default: 'Hello Claude'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test Claude Code Action
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          model: 'sonnet-4'
          workflow_dispatch_prompt: |
            ${{ github.event.inputs.message }}
            
      - name: Show Result
        run: |
          echo "Claude responded successfully!"