name: Claude Official OAuth

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@claude')
    
    steps:
      # 公式ドキュメントに基づく正しい設定
      - uses: anthropics/claude-code-action@v1
        with:
          # Claude Pro/Max用のOAuth設定（ドキュメントから推測）
          anthropic-api-key: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}