name: Debug Test

on:
  issue_comment:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@test')
    steps:
      - name: Echo test
        run: |
          echo "✅ Workflow triggered successfully!"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Comment author: ${{ github.event.comment.user.login }}"
          echo "Comment body: ${{ github.event.comment.body }}"
          
      - name: Add reaction
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            });