name: Simple Push Test

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: |
          echo "✅ GitHub Actions is working!"
          echo "Time: $(date)"
          echo "Repository: ${{ github.repository }}"
          echo "This proves workflows can run in this repository"