name: Test OAuth Token

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  test-token:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Secrets
        run: |
          echo "🔍 Checking OAuth Token Configuration"
          echo "====================================="
          echo ""
          
          # トークンが設定されているか確認（値は表示しない）
          if [ -n "${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}" ]; then
            echo "✅ CLAUDE_CODE_OAUTH_TOKEN is set"
            echo "   Length: ${#CLAUDE_CODE_OAUTH_TOKEN} characters"
          else
            echo "❌ CLAUDE_CODE_OAUTH_TOKEN is NOT set"
          fi
          
          echo ""
          echo "📝 Using OAuth token in claude-code-action"
          
      - name: Test Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          CLAUDE_DEBUG: true